version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8081" # Map port 8081 on the host to port 8081 in the container
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PASS=${DB_PASS} # For pgTables.js
      - SESSION_SECRET=${SESSION_SECRET} # Ensure this is the same as in server.js
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} # For Passport.js
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} # For Passport.js
      - USER_TO_CHECK=${USER_TO_CHECK} # For email checking
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
